name: Build and Test

on:
  push:
    branches: ['git_action']
  pull_request:
    branches: ['git_action']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        mongodb-version: ['6.0']

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        start: npm run start:test
        wait-on: http://localhost:3030

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: eu-west-2

    # - name: Deploy to S3
    #   run: |
    #     aws s3 sync . s3://${{ secrets.cavalieri-acebookproject}} --exclude ".git/*" --exclude "node_modules/*" --delete
 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@git_action
    - uses: mkb93/acebook-node-template@git_action
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}