name: Build and Test

on:
  push:
    branches: ['git_action']
  pull_request:
    branches: ['git_action']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Cypress run
      uses: cypress-io/github-action@v6
      # with:
        # start: npm run start:test
        # wait-on: http://localhost:3030

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION }}

    # - name: Deploy to S3
    #   run: |
    #     aws s3 sync . s3://${{ secrets.cavalieri-acebookproject}} --exclude ".git/*" --exclude "node_modules/*" --delete